local P=game:GetService("Players") local p=P.LocalPlayer local mF=math.floor local mR=math.round local mC=math.clamp local mRa=math.rad local sL=string.lower local sF=string.find local sU=string.upper local sS=string.sub
local C_ID={2959681,9216315975,88189937} local A_ID={1870899605,7668266040} local V_ID={648989434,9987756245}
local function cAu(id) for _,v in pairs(C_ID) do if v==id then return true end end for _,v in pairs(A_ID) do if v==id then return true end end for _,v in pairs(V_ID) do if v==id then return true end end return false end
if not cAu(p.UserId) then return end
local RS=game:GetService("ReplicatedStorage") local RuS=game:GetService("RunService") local UIS=game:GetService("UserInputService") local TS=game:GetService("TeleportService") local CG=game:GetService("CoreGui") local TwS=game:GetService("TweenService")
local tP=(RuS:IsStudio() or not CG) and p:WaitForChild("PlayerGui") or CG local mo=p:GetMouse() local cam=workspace.CurrentCamera local rE=RS:WaitForChild("Modules"):WaitForChild("Events"):WaitForChild("RemoteEvent")
local isM=UIS.TouchEnabled and not UIS.KeyboardEnabled local G_ID=34157675
local A_R={["Marketing"]=true,["Influencer"]=true,["Social Mod"]=true,["Helper"]=true,["Supervisor"]=true,["Manager"]=true,["Contributor"]=true,["Developer"]=true,["Owner"]=true}
local SG=Instance.new("ScreenGui",tP) SG.Name="S7xhub_Panel" SG.ResetOnSpawn=false
if not isM then local NF=Instance.new("TextLabel",SG) NF.Size=UDim2.new(0,350,0,50) NF.Position=UDim2.new(0.5,-175,0.1,0) NF.BackgroundColor3=Color3.fromRGB(0,0,0) NF.BackgroundTransparency=0.2 NF.Text="USE A LETRA G PARA ABRIR E FECHAR O PAINEL" NF.TextColor3=Color3.fromRGB(170,0,255) NF.Font=Enum.Font.GothamBold NF.TextSize=14 Instance.new("UICorner",NF) Instance.new("UIStroke",NF).Color=Color3.fromRGB(170,0,255) task.spawn(function() task.wait(13) TwS:Create(NF,TweenInfo.new(1),{TextTransparency=1,BackgroundTransparency=1}):Play() task.wait(1) NF:Destroy() end) end
local OB=Instance.new("TextButton",SG) OB.Size=UDim2.new(0,45,0,45) OB.Position=UDim2.new(0,10,0.5,-22) OB.BackgroundColor3=Color3.fromRGB(0,0,0) OB.Text="S7" OB.TextColor3=Color3.fromRGB(255,255,255) OB.Font=Enum.Font.GothamBold OB.TextSize=18 OB.Visible=isM Instance.new("UICorner",OB).CornerRadius=UDim.new(1,0) local St=Instance.new("UIStroke",OB) St.Color=Color3.fromRGB(170,0,255) St.Thickness=2
local function cOT(tP,txt,col,mod) local ch=tP.Character or tP.CharacterAdded:Wait() local hd=ch:WaitForChild("Head") if hd:FindFirstChild("S7xTag") then hd.S7xTag:Destroy() end local bb=Instance.new("BillboardGui",hd) bb.Name="S7xTag" bb.Adornee=hd bb.Size=UDim2.new(0,120,0,60) bb.StudsOffset=Vector3.new(0,3,0) bb.AlwaysOnTop=true bb.MaxDistance=100 local lb=Instance.new("TextLabel",bb) lb.BackgroundTransparency=1 lb.Size=UDim2.new(1,0,1,0) lb.Text=txt lb.Font=Enum.Font.GothamBold lb.TextSize=17 lb.TextColor3=col or Color3.fromRGB(255,255,255) lb.TextStrokeTransparency=0.4 if mod=="RGB" then task.spawn(function() local h=0 while bb and bb.Parent do h=h+(1/200) lb.TextColor3=Color3.fromHSV(h,1,1) task.wait() end end) elseif mod=="BW" then task.spawn(function() while bb and bb.Parent do TwS:Create(lb,TweenInfo.new(1.5),{TextColor3=Color3.fromRGB(255,105,180)}):Play() task.wait(2) TwS:Create(lb,TweenInfo.new(1.5),{TextColor3=Color3.fromRGB(255,255,255)}):Play() task.wait(2) end end) end end
local function aST(pl) local function su(c) task.wait(1) if pl==p then cOT(pl,"User",Color3.fromRGB(170,0,255),nil) end for _,id in pairs(C_ID) do if pl.UserId==id then cOT(pl,"Criador",nil,"RGB") end end for _,id in pairs(A_ID) do if pl.UserId==id then cOT(pl,"Admin",nil,"RGB") end end for _,id in pairs(V_ID) do if pl.UserId==id then cOT(pl,"Vip",nil,"BW") end end end pl.CharacterAdded:Connect(su) if pl.Character then su(pl.Character) end end for _,v in pairs(P:GetPlayers()) do aST(v) end P.PlayerAdded:Connect(aST)
local MF=Instance.new("Frame",SG) MF.Name="MainFrame" MF.BackgroundColor3=Color3.fromRGB(15,15,15) MF.Position=UDim2.new(0.05,50,0.2,0) MF.Size=UDim2.new(0,220,0,420) MF.Active=true MF.Draggable=true MF.Visible=true MF.ClipsDescendants=true Instance.new("UICorner",MF).CornerRadius=UDim.new(0,8) Instance.new("UIStroke",MF).Color=Color3.fromRGB(170,0,255)
local TB=Instance.new("Frame",MF) TB.Size=UDim2.new(1,0,0,40) TB.BackgroundTransparency=1 local Ttl=Instance.new("TextLabel",TB) Ttl.Text="S7xhub v1.1.2" Ttl.TextColor3=Color3.fromRGB(255,255,255) Ttl.BackgroundTransparency=1 Ttl.Size=UDim2.new(1,0,1,0) Ttl.Font=Enum.Font.GothamBold Ttl.TextSize=18
task.spawn(function() local h=0 while Ttl and Ttl.Parent do h=h+(1/200) if h>1 then h=0 end Ttl.TextColor3=Color3.fromHSV(h,1,1) task.wait() end end)
local Dv=Instance.new("Frame",MF) Dv.Size=UDim2.new(1,0,0,1) Dv.Position=UDim2.new(0,0,0,40) Dv.BackgroundColor3=Color3.fromRGB(40,40,40) Dv.BorderSizePixel=0 local TM=Instance.new("Frame",MF) TM.Size=UDim2.new(1,0,0,35) TM.Position=UDim2.new(0,0,0,41) TM.BackgroundTransparency=1
local ITB=Instance.new("TextButton",TM) ITB.Size=UDim2.new(0.2,0,1,0) ITB.Text="Início" ITB.BackgroundTransparency=1 ITB.TextColor3=Color3.fromRGB(170,0,255) ITB.Font=Enum.Font.GothamBold ITB.TextSize=9 local FTB=Instance.new("TextButton",TM) FTB.Size=UDim2.new(0.2,0,1,0) FTB.Position=UDim2.new(0.2,0,0,0) FTB.Text="Funções" FTB.BackgroundTransparency=1 FTB.TextColor3=Color3.fromRGB(100,100,100) FTB.Font=Enum.Font.GothamBold FTB.TextSize=9 local CTB=Instance.new("TextButton",TM) CTB.Size=UDim2.new(0.2,0,1,0) CTB.Position=UDim2.new(0.4,0,0,0) CTB.Text="Config" CTB.BackgroundTransparency=1 CTB.TextColor3=Color3.fromRGB(100,100,100) CTB.Font=Enum.Font.GothamBold CTB.TextSize=9 local STB=Instance.new("TextButton",TM) STB.Size=UDim2.new(0.2,0,1,0) STB.Position=UDim2.new(0.6,0,0,0) STB.Text="Specter" STB.BackgroundTransparency=1 STB.TextColor3=Color3.fromRGB(100,100,100) STB.Font=Enum.Font.GothamBold STB.TextSize=9 local ScTB=Instance.new("TextButton",TM) ScTB.Size=UDim2.new(0.2,0,1,0) ScTB.Position=UDim2.new(0.8,0,0,0) ScTB.Text="Scripts" ScTB.BackgroundTransparency=1 ScTB.TextColor3=Color3.fromRGB(100,100,100) ScTB.Font=Enum.Font.GothamBold ScTB.TextSize=9
local IF=Instance.new("Frame",MF) IF.Size=UDim2.new(1,0,1,-76) IF.Position=UDim2.new(0,0,0,76) IF.BackgroundTransparency=1 IF.Visible=true local FF=Instance.new("ScrollingFrame",MF) FF.Size=UDim2.new(1,0,1,-76) FF.Position=UDim2.new(0,0,0,76) FF.BackgroundTransparency=1 FF.ScrollBarThickness=0 FF.Visible=false local FL=Instance.new("UIGridLayout",FF) FL.HorizontalAlignment=Enum.HorizontalAlignment.Center FL.SortOrder=Enum.SortOrder.LayoutOrder FL.CellPadding=UDim2.new(0,6,0,8) FL.CellSize=UDim2.new(0.44,0,0,35) local FP=Instance.new("UIPadding",FF) FP.PaddingTop=UDim.new(0,10)
local CF=Instance.new("ScrollingFrame",MF) CF.Size=UDim2.new(1,0,1,-76) CF.Position=UDim2.new(0,0,0,76) CF.BackgroundTransparency=1 CF.ScrollBarThickness=0 CF.Visible=false local CL=Instance.new("UIListLayout",CF) CL.HorizontalAlignment=Enum.HorizontalAlignment.Center CL.SortOrder=Enum.SortOrder.LayoutOrder CL.Padding=UDim.new(0,8) local CP=Instance.new("UIPadding",CF) CP.PaddingTop=UDim.new(0,10)
local SpF=Instance.new("ScrollingFrame",MF) SpF.Size=UDim2.new(1,0,1,-76) SpF.Position=UDim2.new(0,0,0,76) SpF.BackgroundTransparency=1 SpF.ScrollBarThickness=0 SpF.Visible=false local SpL=Instance.new("UIListLayout",SpF) SpL.HorizontalAlignment=Enum.HorizontalAlignment.Center SpL.SortOrder=Enum.SortOrder.LayoutOrder SpL.Padding=UDim.new(0,6) local SpP=Instance.new("UIPadding",SpF) SpP.PaddingTop=UDim.new(0,10)
local ScF=Instance.new("ScrollingFrame",MF) ScF.Size=UDim2.new(1,0,1,-76) ScF.Position=UDim2.new(0,0,0,76) ScF.BackgroundTransparency=1 ScF.ScrollBarThickness=0 ScF.Visible=false local ScL=Instance.new("UIListLayout",ScF) ScL.HorizontalAlignment=Enum.HorizontalAlignment.Center ScL.SortOrder=Enum.SortOrder.LayoutOrder ScL.Padding=UDim.new(0,8) local ScP=Instance.new("UIPadding",ScF) ScP.PaddingTop=UDim.new(0,10)
local function rT() IF.Visible=false; FF.Visible=false; CF.Visible=false; SpF.Visible=false; ScF.Visible=false ITB.TextColor3=Color3.fromRGB(100,100,100) FTB.TextColor3=Color3.fromRGB(100,100,100) CTB.TextColor3=Color3.fromRGB(100,100,100) STB.TextColor3=Color3.fromRGB(100,100,100) ScTB.TextColor3=Color3.fromRGB(100,100,100) end
ITB.MouseButton1Click:Connect(function() rT(); IF.Visible=true; ITB.TextColor3=Color3.fromRGB(170,0,255) end) FTB.MouseButton1Click:Connect(function() rT(); FF.Visible=true; FTB.TextColor3=Color3.fromRGB(170,0,255) end) CTB.MouseButton1Click:Connect(function() rT(); CF.Visible=true; CTB.TextColor3=Color3.fromRGB(170,0,255) end) STB.MouseButton1Click:Connect(function() rT(); SpF.Visible=true; STB.TextColor3=Color3.fromRGB(170,0,255) end) ScTB.MouseButton1Click:Connect(function() rT(); ScF.Visible=true; ScTB.TextColor3=Color3.fromRGB(170,0,255) end)
local Av=Instance.new("ImageLabel",IF) Av.Size=UDim2.new(0,80,0,80) Av.Position=UDim2.new(0.5,-40,0.05,0) Av.Image="rbxthumb://type=AvatarHeadShot&id="..p.UserId.."&w=150&h=150" Av.BackgroundColor3=Color3.fromRGB(30,30,30) Instance.new("UICorner",Av).CornerRadius=UDim.new(1,0) Instance.new("UIStroke",Av).Color=Color3.fromRGB(170,0,255)
local PN=Instance.new("TextLabel",IF) PN.Size=UDim2.new(1,0,0,20) PN.Position=UDim2.new(0,0,0.35,0) PN.Text=p.DisplayName PN.TextColor3=Color3.fromRGB(255,255,255) PN.BackgroundTransparency=1 PN.Font=Enum.Font.GothamBold PN.TextSize=16
local function gMT() for _,v in pairs(C_ID) do if v==p.UserId then return "Criador" end end for _,v in pairs(A_ID) do if v==p.UserId then return "Admin" end end for _,v in pairs(V_ID) do if v==p.UserId then return "Vip" end end return "User" end
local PT=Instance.new("TextLabel",IF) PT.Size=UDim2.new(1,0,0,20) PT.Position=UDim2.new(0,0,0.45,0) PT.Text="Tag Equipada: "..gMT() PT.TextColor3=Color3.fromRGB(170,0,255) PT.BackgroundTransparency=1 PT.Font=Enum.Font.GothamSemibold PT.TextSize=13
local PL=Instance.new("TextLabel",IF) PL.Size=UDim2.new(1,0,0,20) PL.Position=UDim2.new(0,0,0.55,0) PL.Text="Ping: Calculando..." PL.TextColor3=Color3.fromRGB(200,200,200) PL.BackgroundTransparency=1 PL.Font=Enum.Font.GothamSemibold PL.TextSize=13
task.spawn(function() while task.wait(1) do if PL and PL.Parent then pcall(function() local pV=mR(p:GetNetworkPing()*1000) PL.Text="Ping: "..pV.." ms" end) else break end end end)
local UIL=Instance.new("TextLabel",IF) UIL.Size=UDim2.new(1,0,0,20) UIL.Position=UDim2.new(0,0,0.65,0) UIL.Text="ID da Conta: "..p.UserId UIL.TextColor3=Color3.fromRGB(200,200,200) UIL.BackgroundTransparency=1 UIL.Font=Enum.Font.GothamSemibold UIL.TextSize=13
local cD=os.date("%d/%m/%Y",os.time()-(p.AccountAge*86400)) local AAL=Instance.new("TextLabel",IF) AAL.Size=UDim2.new(1,0,0,20) AAL.Position=UDim2.new(0,0,0.75,0) AAL.Text="Criada em: "..cD AAL.TextColor3=Color3.fromRGB(200,200,200) AAL.BackgroundTransparency=1 AAL.Font=Enum.Font.GothamSemibold AAL.TextSize=13
local CLb=Instance.new("TextLabel",IF) CLb.Size=UDim2.new(1,0,0,20) CLb.Position=UDim2.new(0,0,0.88,0) CLb.Text="Criadores, Lulu Hirosh" CLb.TextColor3=Color3.fromRGB(80,80,80) CLb.BackgroundTransparency=1 CLb.Font=Enum.Font.Gotham CLb.TextSize=11
local bK={Spam=Enum.KeyCode.F,SpamCamera=Enum.KeyCode.C,Esp=Enum.KeyCode.E,Tp=Enum.KeyCode.Q,Fly=Enum.KeyCode.T,Speed=Enum.KeyCode.Y,Noclip=Enum.KeyCode.N}
local fSV=50 local wSV=50
local function aKB(btn,act,dKN) local kB=Instance.new("TextBox",btn) kB.Size=UDim2.new(0,22,0,22) kB.Position=UDim2.new(1,-26,0.5,-11) kB.BackgroundColor3=Color3.fromRGB(40,40,40) kB.TextColor3=Color3.fromRGB(170,0,255) kB.Font=Enum.Font.GothamBold kB.TextSize=11 kB.Text=dKN kB.PlaceholderText="" Instance.new("UICorner",kB).CornerRadius=UDim.new(0,4) kB.FocusLost:Connect(function() local iC=sU(sS(kB.Text,1,1)) local s,c=pcall(function() return Enum.KeyCode[iC] end) if s and c and iC~="" then bK[act]=c kB.Text=iC if act=="Spam" and not iSp then btn.Text="SPAM OVO ["..iC.."]" end if act=="SpamCamera" and not sCA then btn.Text="SPAM CAMERA ["..iC.."]" end if act=="Esp" and not eEn then btn.Text="ESP ["..iC.."]" end if act=="Tp" and not tEn then btn.Text="CLICK TP ["..iC.."]" end if act=="Fly" and not fEn then btn.Text="FLY ["..iC.."]: OFF" end if act=="Speed" and not sEn then btn.Text="SPEED ["..iC.."]: OFF" end if act=="Noclip" and not nEn then btn.Text="NOCLIP ["..iC.."]: OFF" end else kB.Text=bK[act].Name end end) end
local function aVB(btn,iV,cb) local vB=Instance.new("TextBox",btn) vB.Size=UDim2.new(0,30,0,22) vB.Position=UDim2.new(1,-60,0.5,-11) vB.BackgroundColor3=Color3.fromRGB(40,40,40) vB.TextColor3=Color3.fromRGB(0,255,150) vB.Font=Enum.Font.GothamBold vB.TextSize=11 vB.Text=tostring(iV) vB.PlaceholderText="" Instance.new("UICorner",vB).CornerRadius=UDim.new(0,4) vB.FocusLost:Connect(function() local n=tonumber(vB.Text) if n then n=mC(mR(n),0,100) vB.Text=tostring(n) cb(n) else vB.Text=tostring(iV) cb(iV) end end) end
local function cB(t,pr) local b=Instance.new("TextButton",pr) b.Text=t b.BackgroundColor3=Color3.fromRGB(28,28,28) b.TextColor3=Color3.fromRGB(200,200,200) b.Size=UDim2.new(0.85,0,0,30) b.Font=Enum.Font.GothamSemibold b.TextSize=10 Instance.new("UICorner",b).CornerRadius=UDim.new(0,6) return b end
local SB=cB("SPAM OVO ["..bK.Spam.Name.."]",FF) local SCB=cB("SPAM CAMERA ["..bK.SpamCamera.Name.."]",FF) local FB=cB("PEGAR OVOS",FF) local EB=cB("ESP ["..bK.Esp.Name.."]",FF) local TBn=cB("CLICK TP ["..bK.Tp.Name.."]",FF) local RB=cB("REJOIN",FF) local AAB=cB("AntiADM: OFF",FF)
aKB(SB,"Spam",bK.Spam.Name) aKB(SCB,"SpamCamera",bK.SpamCamera.Name) aKB(EB,"Esp",bK.Esp.Name) aKB(TBn,"Tp",bK.Tp.Name) FF.CanvasSize=UDim2.new(0,0,0,180)
local FlB=cB("FLY ["..bK.Fly.Name.."]: OFF",CF) local SpB=cB("SPEED ["..bK.Speed.Name.."]: OFF",CF) local NB=cB("NOCLIP ["..bK.Noclip.Name.."]: OFF",CF) local AAfB=cB("AntiAFK: OFF",CF)
FlB.Size=UDim2.new(0.85,0,0,35) SpB.Size=UDim2.new(0.85,0,0,35) NB.Size=UDim2.new(0.85,0,0,35) AAfB.Size=UDim2.new(0.85,0,0,35) CF.CanvasSize=UDim2.new(0,0,0,4*43+20)
aKB(FlB,"Fly",bK.Fly.Name) aKB(SpB,"Speed",bK.Speed.Name) aKB(NB,"Noclip",bK.Noclip.Name) aVB(FlB,fSV,function(v) fSV=v end) aVB(SpB,wSV,function(v) wSV=v end)
local aAE=false local aAC=nil AAfB.MouseButton1Click:Connect(function() aAE=not aAE AAfB.Text=aAE and "AntiAFK: ON" or "AntiAFK: OFF" AAfB.BackgroundColor3=aAE and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) if aAE then aAC=p.Idled:Connect(function() local vU=game:GetService("VirtualUser") vU:CaptureController() vU:ClickButton2(Vector2.new()) end) else if aAC then aAC:Disconnect() aAC=nil end end end)
local IYB=cB("Infinite Yield",ScF) local VCB=cB("VC CRASHER",ScF) local KB=cB("Ksx",ScF) IYB.Size=UDim2.new(0.85,0,0,35) VCB.Size=UDim2.new(0.85,0,0,35) KB.Size=UDim2.new(0.85,0,0,35)
IYB.MouseButton1Click:Connect(function() loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))() end) VCB.MouseButton1Click:Connect(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Rootleak/Stalkie-2.0/refs/heads/main/vc.lua"))() end) KB.MouseButton1Click:Connect(function() loadstring(game:HttpGet('https://gitlab.com/ksx1s/ksx-s/raw/main/Panel'))() end) ScF.CanvasSize=UDim2.new(0,0,0,3*43+20)
nEn=false local nC=nil local function tN() nEn=not nEn NB.Text=nEn and "NOCLIP ["..bK.Noclip.Name.."]: ON" or "NOCLIP ["..bK.Noclip.Name.."]: OFF" NB.BackgroundColor3=nEn and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) if nEn then nC=RuS.Stepped:Connect(function() local ch=p.Character if ch then for _,pt in pairs(ch:GetDescendants()) do if pt:IsA("BasePart") and pt.CanCollide then pt.CanCollide=false end end end end) else if nC then nC:Disconnect() nC=nil end end end NB.MouseButton1Click:Connect(tN)
fEn=false local fBV,fBG local function tF() fEn=not fEn local ch=p.Character if fEn and ch and ch:FindFirstChild("HumanoidRootPart") then local hrp=ch.HumanoidRootPart local hum=ch:FindFirstChild("Humanoid") if hum then hum.PlatformStand=true end fBG=Instance.new("BodyGyro",hrp) fBG.P=9e4 fBG.maxTorque=Vector3.new(9e9,9e9,9e9) fBG.cframe=hrp.CFrame fBV=Instance.new("BodyVelocity",hrp) fBV.velocity=Vector3.new(0,0.1,0) fBV.maxForce=Vector3.new(9e9,9e9,9e9) FlB.Text="FLY ["..bK.Fly.Name.."]: ON" FlB.BackgroundColor3=Color3.fromRGB(60,60,60) else if ch and ch:FindFirstChild("Humanoid") then ch.Humanoid.PlatformStand=false ch.Humanoid:ChangeState(Enum.HumanoidStateType.Freefall) end if fBG then fBG:Destroy() fBG=nil end if fBV then fBV:Destroy() fBV=nil end FlB.Text="FLY ["..bK.Fly.Name.."]: OFF" FlB.BackgroundColor3=Color3.fromRGB(28,28,28) end end
RuS.RenderStepped:Connect(function() if fEn and fBV and fBG and p.Character and p.Character:FindFirstChild("HumanoidRootPart") then local cCF=cam.CFrame local mD=Vector3.new(0,0,0) if UIS:IsKeyDown(Enum.KeyCode.W) then mD=mD+cCF.LookVector end if UIS:IsKeyDown(Enum.KeyCode.S) then mD=mD-cCF.LookVector end if UIS:IsKeyDown(Enum.KeyCode.A) then mD=mD-cCF.RightVector end if UIS:IsKeyDown(Enum.KeyCode.D) then mD=mD+cCF.RightVector end if UIS:IsKeyDown(Enum.KeyCode.Space) then mD=mD+Vector3.new(0,1,0) end if UIS:IsKeyDown(Enum.KeyCode.LeftShift) or UIS:IsKeyDown(Enum.KeyCode.LeftControl) then mD=mD-Vector3.new(0,1,0) end fBG.cframe=cCF*CFrame.Angles(mRa(-90),0,0) if mD.Magnitude>0 then fBV.velocity=mD.Unit*fSV else fBV.velocity=Vector3.new(0,0.1,0) end end end) FlB.MouseButton1Click:Connect(tF)
sEn=false local function tS() sEn=not sEn SpB.Text=sEn and "SPEED ["..bK.Speed.Name.."]: ON" or "SPEED ["..bK.Speed.Name.."]: OFF" SpB.BackgroundColor3=sEn and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) if not sEn and p.Character and p.Character:FindFirstChild("Humanoid") then p.Character.Humanoid.WalkSpeed=16 end end RuS.RenderStepped:Connect(function() if sEn and p.Character and p.Character:FindFirstChild("Humanoid") then p.Character.Humanoid.WalkSpeed=wSV end end) SpB.MouseButton1Click:Connect(tS)
local aAdE=false local function sAW(nm) local WL=Instance.new("TextLabel",SG) WL.Size=UDim2.new(1,0,0,50) WL.Position=UDim2.new(0,0,0.05,0) WL.BackgroundTransparency=1 WL.Text="⚠️ ADM ENTROU NO SERVIDOR: "..nm.." ⚠️" WL.TextColor3=Color3.fromRGB(255,0,0) WL.Font=Enum.Font.GothamBold WL.TextSize=24 WL.TextStrokeTransparency=0 task.spawn(function() task.wait(20) TwS:Create(WL,TweenInfo.new(1),{TextTransparency=1}):Play() task.wait(1) WL:Destroy() end) end
P.PlayerAdded:Connect(function(nP) if aAdE then local rl=nP:GetRoleInGroup(G_ID) if A_R[rl] then sAW(nP.Name) end end end) AAB.MouseButton1Click:Connect(function() aAdE=not aAdE AAB.Text=aAdE and "AntiADM: ON" or "AntiADM: OFF" AAB.BackgroundColor3=aAdE and Color3.fromRGB(150,0,0) or Color3.fromRGB(28,28,28) end)
local sPl=nil local sE=false local sCo=nil local SAv=Instance.new("ImageLabel",SpF) SAv.Size=UDim2.new(0,60,0,60) SAv.BackgroundTransparency=1 SAv.Image="" Instance.new("UICorner",SAv).CornerRadius=UDim.new(1,0) local SNL=Instance.new("TextLabel",SpF) SNL.Size=UDim2.new(0.9,0,0,20) SNL.BackgroundTransparency=1 SNL.Text="Ninguém selecionado" SNL.TextColor3=Color3.fromRGB(255,255,255) SNL.Font=Enum.Font.GothamBold SNL.TextSize=12 local SSB=Instance.new("TextBox",SpF) SSB.Size=UDim2.new(0.85,0,0,25) SSB.BackgroundColor3=Color3.fromRGB(30,30,30) SSB.TextColor3=Color3.fromRGB(255,255,255) SSB.Font=Enum.Font.GothamSemibold SSB.TextSize=12 SSB.PlaceholderText="Digitar Username/Nome..." SSB.Text="" Instance.new("UICorner",SSB).CornerRadius=UDim.new(0,6)
local function sST(tP) if not tP then return end sPl=tP SNL.Text=tP.DisplayName.." (@"..tP.Name..")" SAv.Image="rbxthumb://type=AvatarHeadShot&id="..tP.UserId.."&w=150&h=150" if tP.Character and tP.Character:FindFirstChild("Humanoid") then cam.CameraSubject=tP.Character.Humanoid end end
SSB.FocusLost:Connect(function() local tx=sL(SSB.Text) for _,pl in pairs(P:GetPlayers()) do if sF(sL(pl.Name),tx) or sF(sL(pl.DisplayName),tx) then sST(pl) break end end SSB.Text="" end)
local STB=cB("Ir até (TP)",SpF) STB.BackgroundColor3=Color3.fromRGB(0,150,0) local SSiB=cB("Sentar: OFF",SpF) local SStB=cB("Parar Spect",SpF) SStB.BackgroundColor3=Color3.fromRGB(200,0,0) SpF.CanvasSize=UDim2.new(0,0,0,60+20+25+35*3+40)
STB.MouseButton1Click:Connect(function() if sPl and sPl.Character and sPl.Character:FindFirstChild("HumanoidRootPart") then if p.Character and p.Character:FindFirstChild("HumanoidRootPart") then p.Character.HumanoidRootPart.CFrame=sPl.Character.HumanoidRootPart.CFrame end end end)
SSiB.MouseButton1Click:Connect(function() sE=not sE SSiB.Text=sE and "Sentar: ON" or "Sentar: OFF" SSiB.BackgroundColor3=sE and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) if sCo then sCo:Disconnect() sCo=nil end if sE then sCo=RuS.Heartbeat:Connect(function() if sPl and sPl.Character and p.Character then local tH=sPl.Character:FindFirstChild("HumanoidRootPart") local mH=p.Character:FindFirstChild("HumanoidRootPart") local mHu=p.Character:FindFirstChild("Humanoid") if tH and mH and mHu then mHu.Sit=true mH.CFrame=tH.CFrame*CFrame.new(0,1.5,0) end end end) else local mHu=p.Character and p.Character:FindFirstChild("Humanoid") if mHu then mHu.Sit=false mHu.Jump=true end end end)
SStB.MouseButton1Click:Connect(function() sPl=nil SNL.Text="Ninguém selecionado" SAv.Image="" if p.Character and p.Character:FindFirstChild("Humanoid") then cam.CameraSubject=p.Character.Humanoid end if sE then sE=false SSiB.Text="Sentar: OFF" SSiB.BackgroundColor3=Color3.fromRGB(28,28,28) if sCo then sCo:Disconnect() sCo=nil end local mHu=p.Character and p.Character:FindFirstChild("Humanoid") if mHu then mHu.Sit=false mHu.Jump=true end end end)
local pO=true local pTS=UDim2.new(0,220,0,420) local function tP() pO=not pO if pO then MF.Size=UDim2.new(0,0,0,0) MF.Visible=true TwS:Create(MF,TweenInfo.new(0.4,Enum.EasingStyle.Quart,Enum.EasingDirection.Out),{Size=pTS}):Play() else local tw=TwS:Create(MF,TweenInfo.new(0.3,Enum.EasingStyle.Quart,Enum.EasingDirection.In),{Size=UDim2.new(0,0,0,0)}) tw:Play() task.spawn(function() tw.Completed:Wait() if not pO then MF.Visible=false end end) end end OB.MouseButton1Click:Connect(tP)
RB.MouseButton1Click:Connect(function() if #P:GetPlayers()<=1 then TS:Teleport(game.PlaceId,p) else TS:TeleportToPlaceInstance(game.PlaceId,game.JobId,p) end end)
tEn=false local function tT() tEn=not tEn TBn.Text=tEn and "CLICK TP: ON" or "CLICK TP ["..bK.Tp.Name.."]" TBn.BackgroundColor3=tEn and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) end TBn.MouseButton1Click:Connect(tT) mo.Button1Down:Connect(function() if tEn and p.Character and p.Character:FindFirstChild("HumanoidRootPart") then p.Character.HumanoidRootPart.CFrame=CFrame.new(mo.Hit.Position+Vector3.new(0,3,0)) end end)
iSp=false local spC=nil local function tgSp() iSp=not iSp SB.Text=iSp and "SPAM OVO: ON" or "SPAM OVO ["..bK.Spam.Name.."]" SB.BackgroundColor3=iSp and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) if iSp then spC=RuS.Heartbeat:Connect(function() local cF=workspace:FindFirstChild("Characters") local tg=cF and cF:FindFirstChild(p.Name) and cF[p.Name]:FindFirstChild("Storegg") if tg then pcall(function() rE:FireServer("TryStoregg",tg,mo.Hit.Position) end) end end) elseif spC then spC:Disconnect() spC=nil end end SB.MouseButton1Click:Connect(tgSp)
sCA=false local dPF=20 local function tSC() sCA=not sCA SCB.Text=sCA and "SPAM CAMERA: ON" or "SPAM CAMERA ["..bK.SpamCamera.Name.."]" SCB.BackgroundColor3=sCA and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) end SCB.MouseButton1Click:Connect(tSC)
RuS.Heartbeat:Connect(function() if not sCA then return end local ch=workspace:FindFirstChild("Characters") and workspace.Characters:FindFirstChild(p.Name) local rm=ch and ch:FindFirstChild("Camera") and ch.Camera:FindFirstChild("Remote") if rm then for i=1,dPF do if not sCA then break end rm:FireServer() end end end)
local isF=false FB.MouseButton1Click:Connect(function() isF=not isF FB.Text=isF and "PEGAR OVOS: ON" or "PEGAR OVOS" FB.BackgroundColor3=isF and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) if isF then task.spawn(function() while isF do local eg=workspace:FindFirstChild("Eggs") if p.Character and eg then for _,ob in pairs(eg:GetChildren()) do if not isF then break end if ob:IsA("Model") and sF(ob.Name,"Egg") then local tp=ob:FindFirstChildWhichIsA("BasePart",true) if tp then p.Character.HumanoidRootPart.CFrame=tp.CFrame*CFrame.new(0,8,0) task.wait(2.5) end end end end task.wait(1) end end) end end)
eEn=false local eF=Instance.new("Folder",SG) local function tgE() eEn=not eEn EB.Text=eEn and "ESP: ON" or "ESP ["..bK.Esp.Name.."]" EB.BackgroundColor3=eEn and Color3.fromRGB(60,60,60) or Color3.fromRGB(28,28,28) if not eEn then eF:ClearAllChildren() end end EB.MouseButton1Click:Connect(tgE)
task.spawn(function() while task.wait() do if eEn then for _,v in pairs(P:GetPlayers()) do if v~=p and v.Character and v.Character:FindFirstChild("Head") then local b=eF:FindFirstChild(v.Name) or Instance.new("BillboardGui",eF) b.Name=v.Name b.Adornee=v.Character.Head b.Size=UDim2.new(0,100,0,50) b.AlwaysOnTop=true local l=b:FindFirstChild("L") or Instance.new("TextLabel",b) l.Name="L" l.Size=UDim2.new(1,0,1,0) l.BackgroundTransparency=1 l.Font=Enum.Font.GothamBold l.TextSize=14 local r=v:GetRoleInGroup(G_ID) local d=mF((p.Character.HumanoidRootPart.Position-v.Character.HumanoidRootPart.Position).Magnitude) if A_R[r] then l.TextColor3=Color3.fromRGB(255,0,0) l.Text=v.Name.."\n["..r.."]\n"..d.."m" else l.TextColor3=Color3.fromRGB(255,255,255) l.Text=v.Name.."\n"..d.."m" end end end end end end)
UIS.InputBegan:Connect(function(i,pr) if pr then return end if i.KeyCode==Enum.KeyCode.G then tP() end if i.KeyCode==bK.Spam then tgSp() end if i.KeyCode==bK.SpamCamera then tSC() end if i.KeyCode==bK.Esp then tgE() end if i.KeyCode==bK.Tp then tT() end if i.KeyCode==bK.Fly then tF() end if i.KeyCode==bK.Speed then tS() end if i.KeyCode==bK.Noclip then tN() end end)
